#!/bin/bash
printf "\n\e[0;32m🍣   Optimizing...\e[0m\n\n"
node_modules/.bin/elm make src/Internal/Main.elm --output=js/temp.js --optimize
node_modules/.bin/terser js/temp.js --no-rename --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters=true,keep_fargs=false,unsafe_comps=true,unsafe=true,passes=2' --mangle --output=js/elm.js
rm js/temp.js
